import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ maxWidth: "40rem" }}>
        <h1>hacker_sundae</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac nibh
          sit amet odio vehicula congue. Class aptent taciti sociosqu ad litora
          torquent per conubia nostra, per inceptos himenaeos. Aenean dignissim
          lorem libero, in pharetra nisi luctus vel. Nulla interdum quam id
          vestibulum fringilla. Vivamus metus massa, pharetra sagittis sodales
          sed, tempor a sapien. Donec a velit non diam mollis faucibus. Sed vel
          velit at ex dictum tincidunt. Nunc eu convallis tellus. Vivamus
          interdum sollicitudin suscipit. Morbi mi elit, sagittis sit amet nisi
          vitae, vestibulum gravida mi. Sed et arcu ac ipsum lacinia posuere
          vitae quis ipsum. Nam vulputate sollicitudin finibus. Duis gravida dui
          eget vestibulum gravida.
        </p>
        <p>
          Donec et massa diam. Nunc ac turpis lorem. Nam erat felis, interdum
          nec ante eu, semper venenatis magna. In efficitur, metus finibus
          fringilla tincidunt, est libero commodo massa, id tempus turpis risus
          vitae diam. Vivamus quam dolor, iaculis id venenatis convallis,
          sodales at lacus. Praesent ac leo et nisl accumsan ornare sed non
          risus. Praesent id dignissim tortor. Maecenas mi turpis, ultricies ac
          ultrices vel, consectetur euismod turpis. Nunc est ipsum, porta nec
          nunc ut, gravida ornare diam.
        </p>
        <section className={styles.links}>
          <a href="" target="_blank" rel="noopener noreferrer">
            Join the discord
          </a>
        </section>
      </main>

      <footer className={styles.footer}>
        <span style={{ display: "flex", gap: "8px" }}>
          <p>made with</p>
          <a href="" target="_blank" rel="noopener noreferrer">
            &hearts;
          </a>
          <a href="" target="_blank" rel="noopener noreferrer">
            &hearts;
          </a>
        </span>
      </footer>
    </div>
  );
};

export default Home;
