name: prettier

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-web
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run prettier
      run: yarn run prettier --check .
