name: prettier
on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: |
          pwd
          yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn run prettier --check .
